version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - eval $(aws ecr get-login)
  build:
    commands:
      - aws s3 cp s3://docker-ecs-simple/simplewebapptest.war simplewebapp.war    
  post_build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t simplewebapp --build-arg WEBCONTEXT=$WEBCONTEXT .
      - docker tag simplewebapp:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_REPO_NAME:latest
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_REPO_NAME:latest